### ISSUE TITLE
Setup WordPress

### ISSUE THREAD

**Issue by catherinephan** [asu-cis-capstone/sphere#14]
To be determined if we will be using WordPress

**Comment by ghost** [comment]
Installed Theme:
Sparkling 1.9.3 (for testing purposes)

Installed Plugins:
WordPress SEO by YOAST 2.3.4
Akismet 3.1.3 (Provides comment SPAM filtering)
JetPack 3.7 (provides enhanced feature set and mobile theme.
Custom Facebook Feed 2.3.7
The Events Calendar 3.12.1
